@extends('layouts.app')
@section('title', 'Rental Tenants')
@section('page_heading', 'Rental Tenants')
@section('content')
@include('rental-management::partials-style')
<div class="rm-page">
@if(session('success'))<div class="rm-alert">{{ session('success') }}</div>@endif
<div class="rm-hero"><div><h1>Tenants</h1><p>Add tenants and assign them to vacant rooms.</p></div><div class="rm-actions"><a class="rm-btn secondary" href="{{ route('rental-management.dashboard') }}">Dashboard</a><a class="rm-btn" href="{{ route('rental-management.invoices.index') }}">Invoices</a></div></div>
<div class="rm-card"><form class="rm-form" method="POST" action="{{ route('rental-management.tenants.store') }}">@csrf<input name="name" placeholder="Tenant name" required><input name="phone" placeholder="Phone"><input type="email" name="email" placeholder="Email"><input name="guardian_phone" placeholder="Guardian phone"><select name="property_id"><option value="">Property optional</option>@foreach($properties as $property)<option value="{{ $property->id }}">{{ $property->name }}</option>@endforeach</select><select name="unit_id"><option value="">Select vacant unit</option>@foreach($units as $unit)<option value="{{ $unit->id }}">{{ $unit->unit_number }} - {{ $unit->property?->name }}</option>@endforeach</select><input type="date" name="move_in_date"><input type="number" step="0.01" name="rent_balance" placeholder="Opening balance"><textarea name="notes" placeholder="Notes"></textarea><button class="rm-btn" type="submit">Add Tenant</button></form>
<table class="rm-table"><thead><tr><th>Tenant</th><th>Property</th><th>Unit</th><th>Balance</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($tenants as $tenant)<tr><td><strong>{{ $tenant->name }}</strong><br><span class="rm-muted">{{ $tenant->phone }}</span></td><td>{{ $tenant->property?->name ?? '-' }}</td><td>{{ $tenant->unit?->unit_number ?? '-' }}</td><td>KES {{ number_format($tenant->rent_balance, 2) }}</td><td><span class="rm-badge {{ $tenant->status }}">{{ ucfirst(str_replace('_',' ',$tenant->status)) }}</span></td><td>@if($tenant->status === 'active')<form method="POST" action="{{ route('rental-management.tenants.move-out', $tenant) }}">@csrf<button class="rm-btn secondary" type="submit">Move Out</button></form>@else - @endif</td></tr>@empty<tr><td colspan="6" class="rm-empty">No tenants yet.</td></tr>@endforelse</tbody></table>@if(method_exists($tenants,'links'))<div class="rm-pagination">{{ $tenants->links() }}</div>@endif</div>
</div>
@endsection
