@extends('layouts.app')
@section('title', 'Rental Invoices')
@section('page_heading', 'Rental Invoices')
@section('content')
@include('rental-management::partials-style')
<div class="rm-page">
@if(session('success'))<div class="rm-alert">{{ session('success') }}</div>@endif
<div class="rm-hero"><div><h1>Invoices & Payments</h1><p>Bill tenants for rent, water, internet, deposits, and other charges.</p></div><div class="rm-actions"><a class="rm-btn secondary" href="{{ route('rental-management.dashboard') }}">Dashboard</a><a class="rm-btn" href="{{ route('rental-management.tenants.index') }}">Tenants</a></div></div>
<div class="rm-card"><form class="rm-form" method="POST" action="{{ route('rental-management.invoices.store') }}">@csrf<select name="tenant_id" required><option value="">Select tenant</option>@foreach($tenants as $tenant)<option value="{{ $tenant->id }}">{{ $tenant->name }} - {{ $tenant->phone }}</option>@endforeach</select><select name="invoice_type" required><option value="rent">Rent</option><option value="water">Water</option><option value="internet">Internet</option><option value="deposit">Deposit</option><option value="other">Other</option></select><input type="number" step="0.01" name="amount" placeholder="Amount" required><input type="date" name="billing_month"><input type="date" name="due_date"><textarea name="notes" placeholder="Notes"></textarea><button class="rm-btn" type="submit">Create Invoice</button></form>
<table class="rm-table"><thead><tr><th>Invoice</th><th>Tenant</th><th>Amount</th><th>Paid</th><th>Status</th><th>Record Payment</th></tr></thead><tbody>@forelse($invoices as $invoice)<tr><td><strong>{{ $invoice->invoice_number }}</strong><br><span class="rm-muted">{{ ucfirst($invoice->invoice_type) }}</span></td><td>{{ $invoice->tenant?->name ?? '-' }}</td><td>KES {{ number_format($invoice->amount, 2) }}</td><td>KES {{ number_format($invoice->paid_amount, 2) }}</td><td><span class="rm-badge {{ $invoice->status }}">{{ ucfirst($invoice->status) }}</span></td><td><form method="POST" action="{{ route('rental-management.invoices.payments.store', $invoice) }}" style="display:grid;grid-template-columns:1fr 1fr auto;gap:6px">@csrf<input name="amount" type="number" step="0.01" placeholder="Amount"><input name="reference" placeholder="Ref"><button class="rm-btn secondary" type="submit">Save</button></form></td></tr>@empty<tr><td colspan="6" class="rm-empty">No invoices yet.</td></tr>@endforelse</tbody></table>@if(method_exists($invoices,'links'))<div class="rm-pagination">{{ $invoices->links() }}</div>@endif</div>
</div>
@endsection
